"""STRIP engine: split a parent bond into Coupon + Principal STRIPS and
normalize their present values to min(book value, market value), per RBI's
2010 Stripping Guidelines.

Frozen signature: ``strip_and_price()`` -- see SPEC.md Section 4 /
technical-schema.md Section 6.1.

Units note (deliberate deviation from technical-schema.md Section 1 -- see
the docstring below): ``parent["coupon"]`` here is the coupon rate as
PERCENT (e.g. 9.39, not 0.0939), even though technical-schema.md Section 6.1
labels it DECIMAL. This isn't a choice -- it's what's required to reproduce
both frozen fixtures (Annex 3 and Annex 4) to their stated tolerances; the
worked examples in technical-schema.md Section 6.4 / SPEC.md Section 5.2
only come out to 2,347,500 (not 23,475) if 9.39 is used directly. Flagged as
a documentation inconsistency to fix under Section 11 change control, not
silently "corrected" here since that would fail both fixtures.
"""

from __future__ import annotations

from typing import Callable

import pandas as pd
from scipy.interpolate import CubicSpline

from src.bond import accrued_30_360, coupon_dates, to_date

TIME_CONVENTIONS = ("act365", "half_year")
SDL_MAX_RESIDUAL_YEARS = 14.0


def _implied_spot_rate(discount_factor: float, t_years: float) -> float:
    """Semiannual zero rate (PERCENT) implied by a discount factor.

    Inverts DF(t) = (1 + z/2) ** (-2t). This is derived straight from
    whatever ``df_func`` returned, so it's consistent regardless of whether
    that came from a real curve or a fixture lookup.
    """
    if t_years <= 0:
        return float("nan")
    return ((discount_factor ** (-1.0 / (2.0 * t_years))) - 1.0) * 2.0 * 100.0


def _parent_tag(parent: dict) -> str:
    """Short disambiguator for Principal STRIP ids.

    ``parent`` only ever carries coupon + maturity (technical-schema.md
    Section 6.1), and maturity is already the row's own date -- so coupon is
    the only other field available to keep two different parents that
    happen to mature on the same day from colliding under the "keyed by
    date AND parent" rule for principal strip_ids. Neither frozen fixture
    actually needs this (no two parents share a maturity date in Annex 3),
    so this only matters for real, non-fixture data.
    """
    return f"{parent['coupon']:.4f}"


def strip_and_price(
    parent: dict,
    face: float,
    settle,
    df_func: Callable[[float], float],
    book_value: float,
    market_value: float,
    time_convention: str = "act365",
) -> pd.DataFrame:
    """Strip ``parent`` into Coupon + Principal STRIPS, normalized to
    min(book_value, market_value).

    parent: {"coupon": PERCENT (see module docstring), "maturity": date-like}
    face: rupees, the face value being stripped. face=100 reproduces Annex 4's
        per-100 illustration; face=50_000_000 reproduces Annex 3's ~5cr
        example -- same formula at any scale (technical-schema.md Sec 6.2).
    settle: date-like: the settlement date. Coupon dates are generated by
        stepping back from ``parent["maturity"]`` in exact 6-month
        increments (reusing bond.coupon_dates, which only needs dates -- no
        coupon -- so it carries none of bond.py's own percent/decimal
        convention with it).
    df_func: t (years) -> discount factor. Real use: a Curve built from
        fbil_sdl_zcyc.csv. Fixture tests: an explicit lookup against a
        fixture's own printed per-period rates.
    book_value, market_value: rupees, ABSOLUTE for the whole ``face`` being
        stripped (not per-100 unless face itself is 100).
    time_convention: "act365" (real pricing, default) or "half_year"
        (integer semiannual period counting -- t = period_index * 0.5,
        period_index = 1, 2, 3, ... -- used only to reproduce the Annex 3/4
        textbook fixtures).

    Returns one row per remaining coupon date (type="coupon") plus one row
    for the principal (type="principal"), columns:
      [strip_id, type, cashflow_date, t_years, cashflow, spot_rate,
       discount_factor, pv, normalized_value, price_per_100]
    """
    if time_convention not in TIME_CONVENTIONS:
        raise ValueError(f"time_convention must be one of {TIME_CONVENTIONS}, got {time_convention!r}")

    coupon = parent["coupon"]
    maturity = parent["maturity"]
    settle_d = to_date(settle)
    dates = coupon_dates(maturity, settle_d)
    if not dates:
        raise ValueError(f"no remaining coupon dates for maturity {maturity} after settle {settle_d}")

    def t_years_for(period_index: int, cashflow_date) -> float:
        if time_convention == "act365":
            return (cashflow_date - settle_d).days / 365.0
        return period_index * 0.5

    rows = []
    for period_index, d in enumerate(dates, start=1):
        t_years = t_years_for(period_index, d)
        cashflow = (coupon / 2.0) * (face / 100.0)
        df = df_func(t_years)
        rows.append(
            {
                "strip_id": f"CS-{d.isoformat()}",
                "type": "coupon",
                "cashflow_date": pd.Timestamp(d),
                "t_years": t_years,
                "cashflow": cashflow,
                "spot_rate": _implied_spot_rate(df, t_years),
                "discount_factor": df,
                "pv": cashflow * df,
            }
        )

    last_date = dates[-1]
    last_period_index = len(dates)
    principal_t = t_years_for(last_period_index, last_date)
    principal_df = df_func(principal_t)
    rows.append(
        {
            "strip_id": f"PS-{last_date.isoformat()}-{_parent_tag(parent)}",
            "type": "principal",
            "cashflow_date": pd.Timestamp(last_date),
            "t_years": principal_t,
            "cashflow": float(face),
            "spot_rate": _implied_spot_rate(principal_df, principal_t),
            "discount_factor": principal_df,
            "pv": face * principal_df,
        }
    )

    out = pd.DataFrame(rows)
    total_pv = out["pv"].sum()
    factor = min(book_value, market_value) / total_pv
    out["normalized_value"] = factor * out["pv"]
    out["price_per_100"] = out["normalized_value"] / out["cashflow"] * 100.0
    return out


# ---------------------------------------------------------------------------
# C2 -- bonus SDL pricing (SPEC.md Section 6 / technical-schema.md Section 6.5)
# ---------------------------------------------------------------------------


def build_sdl_discount_function(sdl_zcyc: pd.DataFrame) -> Callable[[float], float]:
    """t (years) -> discount factor, from FBIL's published SDL ZCYC.

    Cubic-spline interpolates ``zcy_semi`` (percent -> decimal at the
    boundary, per technical-schema.md Sec 1) over ``tenor_years``, then
    applies the standard semiannual DF formula. Flat beyond the published
    grid (0.25-14y) -- mirrors curve.py's own extrapolation policy, needed
    here because a cash flow can land just inside settle, below the grid's
    0.25y floor.
    """
    t = sdl_zcyc["tenor_years"].to_numpy(dtype=float)
    z = sdl_zcyc["zcy_semi"].to_numpy(dtype=float) / 100.0
    spline = CubicSpline(t, z, bc_type="natural")
    t_min, t_max = float(t.min()), float(t.max())
    z_min, z_max = float(z[0]), float(z[-1])

    def df_func(t_years: float) -> float:
        if t_years <= t_min:
            z_t = z_min
        elif t_years >= t_max:
            z_t = z_max
        else:
            z_t = float(spline(t_years))
        return (1.0 + z_t / 2.0) ** (-2.0 * t_years)

    return df_func


def price_sdl(sdl_bond_row, sdl_zcyc: pd.DataFrame, settle, book_value_col: str) -> pd.DataFrame:
    """Price one book-value scenario for the bonus SDL (SPEC.md Section 6).

    sdl_bond_row: a row from sdl_bond.csv (technical-schema.md Sec 2.4).
    sdl_zcyc: fbil_sdl_zcyc.csv, loaded -- the discount curve, NOT the
        headline G-Sec curve (the whole point of the bonus scope decision is
        we borrow FBIL's published SDL curve rather than building our own).
    book_value_col: "book_value_scenario_1" or "book_value_scenario_2".

    market_value = market_price + accrued_30_360(...) (dirty), scaled to
    face_stripped -- reuses bond.accrued_30_360 directly (coupon passed as
    PERCENT, matching both that function's own convention and strip_and_price's
    -- see C_status.md divergence tracker D1/D2, this is not a coincidence
    worth "fixing").
    """
    coupon = float(sdl_bond_row["coupon"])
    maturity = to_date(sdl_bond_row["maturity"])
    settle_d = to_date(settle)
    residual_years = (maturity - settle_d).days / 365.0
    if residual_years > SDL_MAX_RESIDUAL_YEARS:
        raise ValueError(
            f"SDL residual maturity {residual_years:.2f}y exceeds the "
            f"{SDL_MAX_RESIDUAL_YEARS}y SDL ZCYC eligibility limit"
        )

    face = float(sdl_bond_row["face_stripped"])
    dirty_per_100 = float(sdl_bond_row["market_price"]) + accrued_30_360(coupon, maturity, settle_d)
    market_value = dirty_per_100 * (face / 100.0)
    book_value = float(sdl_bond_row[book_value_col])

    parent = {"coupon": coupon, "maturity": maturity}
    df_func = build_sdl_discount_function(sdl_zcyc)
    return strip_and_price(
        parent, face, settle_d, df_func, book_value, market_value, time_convention="act365"
    )
